### ISSUE TITLE
[Joss Review] Readme Update

### ISSUE THREAD

**Issue by Saran-nns** [carnotresearch/cr-sparse#22]
Hi @shailesh1729 

I found the readme is somewhat cluttered. 

Here are a few of my suggestions;

- [x] Quickstart section is not necessary for this readme. I recommend removing it

- [x] Please include the image about the sparse representation problem(at draft summary) below lines[14-25].

- [x] Lines[27-31]  can be replaced by _For detailed documentation and usage_, please visit https://cr-sparse.readthedocs.io/en/latest.

- [x] Lines [34-51] looks redundant. I suggest removing it since you have mentioned the algorithms already in the introduction part and are present in the _Examples_ section also. For more examples please direct the users to the example gallery https://cr-sparse.readthedocs.io/en/latest/gallery/index.html 

- [x] Line 57 is redundant. Remove line 57 and move line 56 to line 73

Thank you and let me know what you think about the suggestions,

**Comment by shailesh1729** [comment]
Thanks, @Saran-nns  for the detailed feedback. A good look by a second pair of eyes really helps in cleaning up things. 

I had done a hack earlier where I was including the `README.rst` also as a quickstart page in the online docs so that I could reuse the text.  This hack was also causing problems in including the image in the README. I have separated the quick start page in online docs from the main README now. 

Hope that the new version of README addresses your concerns and is looking cleaner.

**Comment by Saran-nns** [comment]
Hi @shailesh1729 Looks much better now. Few contents from Quickstart section is still present, lines 8-10. 

Also, I prefer the below order in Readme,
1. Introduction 
2. Supported Platforms 
3. Installation
4. Examples/Usage
5. **Contribution Guidelines/Code of Conduct** You can just provide the link to _Code of Conduct_ that you already have in the repository 
6. Citation

Let me know what you think about the suggestions

**Comment by shailesh1729** [comment]
please check now

**Comment by Saran-nns** [comment]
Looks great :)
